### ISSUE TITLE
Adding a script to test extensions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard_extension_template#1]
I would love to have a script as part of the standard template which I can use to test my extension against current version of OCDS.

E.g. before pushing it an updated version, I would run the test script which would:

* Check my JSON was valid;
* Grab the latest (or specified) version of the OCDS schema, and merge-patch it;
* Present back the output in some meaningful way - possibly by building a little temporary docson viewer;

I've been meaning to write this myself, but not got to it yet, so logging here.

**Comment by kindly** [comment]
Added to this would be testing the patched schema against an example that covers all parts of the core schema and validates. Against the new patched schema this example should also validate.

**Comment by jpmckinney** [comment]
`extension_tester` and this repo's `.travis.yml` file do this now. We can work on improvements to output or workflow in https://github.com/open-contracting/extension_tester and https://github.com/open-contracting/standard-maintenance-scripts
