### ISSUE TITLE
An approach to extend existing codelists

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard_extension_template#2]
For the PPP project we have an number of different extensions which want to add to an existing codelist. For example, adding to documentType.

The current approach lets us over-write codelists, but not add to them. This is a problem when you have multiple interacting codelists. 

Could we develop an approach based on a syntax such as '_codeListName.csv' to append, and 'codeListName.csv' to over-write? 

This depends on:

* Firming up the CSV specification for our codelists (which are currently not terrible consistent and tidy)

**Comment by kindly** [comment]
I think that "+codeListName.csv" and "-codeListName.csv" should be good to add an remove and codeListName.csv to replace.

**Comment by timgdavies** [comment]
I believe this has been partially implemented in some of the work on the PPP profile, but it is not yet fully worked up in all our tools.

**Comment by jpmckinney** [comment]
Moving to https://github.com/open-contracting/standard/issues/584 as the extension template is not the appropriate forum for discussing this issue.
