### ISSUE TITLE
JSON Schema files optional?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard_extension_template#29]
The template has:

> Extensions must include at least one of those files.

However, it's possible, as in https://github.com/INAImexico/ocds_extendedProcurementCategory_extension, to only have a modification to a codelist.

I suspect that the above phrase was written before codelist modification was specified. I propose removing the sentence, to make it allowed to only modify codelists.

Also, there is no consequence to 'no-op' extensions that modify nothing, so we don't need to specifically guard against that.

Agreed, @kindly @timgdavies @duncandewhurst? 

cc @yolile

**Comment by jpmckinney** [comment]
Secondly: I believe CoVE considers an extension to be invalid ('fetching failed') if it has no release-schema.json (note that the template instructions allow extensions to extend package schema without extending the release schema). It shouldn't report that.

In https://github.com/open-contracting/ocds-extensions/issues/59, I propose adding a `schemas` field to extension.json similar to the `codelists` field. I propose that CoVE's behavior should be to error if it tries to fetch a schema listed in `schemas` and fails, but reports no error if there are no `schemas` specified and it fails to optimistically retrieve the release schema.

**Comment by duncandewhurst** [comment]
All sounds good to me
