### ISSUE TITLE
Move "How the extensions work" to OCDS documentation or Extension Explorer

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard_extension_template#37]
https://github.com/open-contracting/standard_extension_template#how-the-extensions-work

**Comment by mrshll1001** [comment]
Has there been a decision whether to move this to OCDS Documentation or the Extension Explorer? If so I'm happy to proceed.

**Comment by jpmckinney** [comment]
Let's move it to the Extension Explorer. You can find a place for it in this doc (still need to put it into website templates): https://docs.google.com/document/d/1JQCOQzLvwEeue6yE4AugyPXQlsC08-ljfUoBwJ4bNWQ/edit

**Comment by jpmckinney** [comment]
Noting that the above document has been integrated into the website in https://github.com/open-contracting/extension-explorer/issues/47

**Comment by duncandewhurst** [comment]
I've moved this content in the draft shared in https://github.com/open-contracting/standard_extension_template/issues/41#issuecomment-2239192221 so I'll close this issue in favour of that one.
